version: "3.3"

services:

  reference-ui:
    image: siglusdevops/reference-ui:latest
    env_file: settings.prod.env
    depends_on: [consul]
    networks:
      - siglus-net
    deploy:
      mode: replicated
      replicas: 3

  requisition:
    image: openlmis/requisition:8.2.2
    env_file: settings.prod.env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - '/home/ubuntu/config:/config'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    networks:
      - siglus-net
    deploy:
      mode: replicated
      replicas: 3

  referencedata:
    image: openlmis/referencedata:15.1.1
    env_file: settings.prod.env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - '/home/ubuntu/config:/config'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    networks:
      - siglus-net
    deploy:
      mode: replicated
      replicas: 3

  auth:
    image: openlmis/auth:4.3.0
    env_file: settings.prod.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - '/home/ubuntu/config:/config'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    networks:
      - siglus-net
    deploy:
      placement:
        constraints: [ node.role == manager ]

  notification:
    image: siglusdevops/notification:latest
    env_file: settings.prod.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - '/home/ubuntu/config:/config'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    networks:
      - siglus-net
    deploy:
      mode: replicated
      replicas: 3

  fulfillment:
    image: openlmis/fulfillment:8.1.1
    env_file: settings.prod.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - '/home/ubuntu/config:/config'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    networks:
      - siglus-net
    deploy:
      mode: replicated
      replicas: 3

  stockmanagement:
    image: openlmis/stockmanagement:5.0.2
    env_file: settings.prod.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - '/home/ubuntu/config:/config'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    networks:
      - siglus-net
    deploy:
      mode: replicated
      replicas: 3

  report:
    image: openlmis/report:1.2.1
    env_file: settings.prod.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - '/home/ubuntu/config:/config'
    depends_on: [log]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    networks:
      - siglus-net
    deploy:
      mode: replicated
      replicas: 3

  siglusapi:
    image: siglusdevops/siglusapi:latest
    env_file: settings.prod.env
    environment:
      JAVA_OPTS: '-server -Xmx2048m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - '/home/ubuntu/config:/config'
    depends_on: [log, requisition, referencedata, auth, notification, fulfillment, stockmanagement]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    networks:
      - siglus-net
    deploy:
      mode: replicated
      replicas: 3

networks:
  siglus-net:
    external: true
