version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: '-Xms2g -Xmx2g'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
      discovery.type: 'single-node'
      network.publish_host: _eth0_
    volumes:
      - /home/ubuntu/esdata:/usr/share/elasticsearch/data
    networks:
      - siglus-net
    deploy:
      placement:
        constraints:
          - node.hostname == elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - siglus-net
    deploy:
      placement:
        constraints:
          - node.hostname == elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
    networks:
      - siglus-net
    deploy:
      placement:
        constraints:
          - node.hostname == elk

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.12.0
    depends_on:
      - elasticsearch
      - kibana
    cap_add: [ "CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID" ]
    cap_drop: [ "ALL" ]
    ports:
      - '8200:8200'
    networks:
      - siglus-net
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
    deploy:
      placement:
        constraints:
          - node.hostname == elk

configs:
  logstash_pipeline:
    file: ./config/logstash.conf

networks:
  siglus-net:
    external: true
