version: "3.3"

services:

  consul:
    image: consul:latest
    networks:
      siglus-net:
        aliases:
          - consul.server
    command: "consul agent -config-file /consul/config/config.json"
    ports:
      - target: 8500
        published: 8500
        mode: host
    volumes:
      - /home/ubuntu/config/consul/server:/consul/config
    deploy:
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.hostname == manager

#  consul-agent:
#    image: consul:latest
#    networks:
#      siglus-net:
#        aliases:
#          - consul.server
#    command: "consul agent -config-file /consul/config/config.json"
#    ports:
#      - target: 8500
#        published: 8500
#        mode: host
#    volumes:
#      - /home/ubuntu/config/consul/agent:/consul/config
#      - /home/ubuntu/consul-data:/consul/data
#    deploy:
#      mode: global
#      endpoint_mode: dnsrr
#      update_config:
#        parallelism: 1
#        failure_action: rollback
#        delay: 30s
#      restart_policy:
#        condition: any
#        delay: 5s
#        window: 120s
#      placement:
#        constraints:
#          - node.hostname != manager
#          - node.hostname != elk

  log:
    image: openlmis/rsyslog:1
    volumes:
      - 'syslog:/var/log'
    depends_on:
      - consul
    networks:
      - siglus-net
    deploy:
      placement:
        constraints:
          - node.hostname == manager

  nginx:
    image: openlmis/nginx:5
    ports:
      - target: 80
        published: 80
        mode: host
    env_file: settings.prod.env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on:
      - consul
    networks:
      - siglus-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname != elk

volumes:
  nginx-log:
    external: false
  consul-template-log:
    external: false
  syslog:
    external: false

networks:
  siglus-net:
    external: true
