version: "3.8"

services:

  sonarqube:
    image: sonarqube:8.8-community
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonarpassword
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /home/ec2-user/sonar/sonarqube_data:/opt/sonarqube/data
      - /home/ec2-user/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - /home/ec2-user/sonar/sonarqube_logs:/opt/sonarqube/logs
      - /home/ec2-user/sonar/sonarqube_temp:/opt/sonarqube/temp

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpassword
    volumes:
      - /home/ec2-user/sonar/postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - /home/ec2-user/sonar/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
